Update .appversions
==> Upgrading coreutils: 
Error: Cannot install coreutils because conflicting formulae are installed.
-- md5sha1sum: because both install `md5sum` and `sha1sum` binaries